### ISSUE TITLE
Support clear notification

### ISSUE THREAD

**Issue by maxwill-max** [versa-syahptr/winotify#12]
sometimes notifications stay in the action center unless cleared manually. is it possible to add a clear notification function?

**Comment by gitagogaming** [comment]
I am here to second this, would love the option to clear notifications

**Comment by versa-syahptr** [comment]
It will be available soon, I'll just do some final checks before release it

**Comment by versa-syahptr** [comment]
Version `1.1.0` has been released, this version includes clear notification support and  callback feature  (#10)  . Please read the [documentation](https://versa-syahptr.github.io/winotify/docs/winotify.html) to learn more.

**Comment by gitagogaming** [comment]
I love the addition of Callback as well, thats a great feature!

Although I've got two issues with this most recent update.

1) I've ran into an issue getting notifications to clear, I've used  your example as my base.(see below)
2) Notifications are no longer popping up visually upon being triggered, although they are still in the notification viewer when clicked..


```
app_id = "WinTools-Notify"
app_path = os.path.abspath(__file__)
r = Registry(app_id, PY_EXE, app_path, force_override=True)
notifier = Notifier(r)

@notifier.register_callback
def clear_notify():
    notifier.clear()


def win_toast(atitle="", amsg="", buttonText = "", buttonlink = "", sound = "", aduration="short", icon=""):
    ### setting the base notification stuff
    if not os.path.exists(rf"{icon}") or icon == "": icon = os.path.join(os.getcwd(),"src\icon.png")

    toast = notifier.create_notification(
                         title=atitle,
                         msg=amsg,
                         icon=icon,
                         duration = aduration.lower(),
                         )
    
    if buttonText != "" and buttonlink != "":
        toast.add_actions(label=buttonText, 
                        launch=buttonlink)
        toast.add_actions("Open Github", "https://github.com/versa-syahptr/winotify")
        toast.add_actions("Quit app", "Kewl")
        toast.add_actions("spam", "sweet")

    toast.build()
    toast.show()
    clear_notify()

**Comment by versa-syahptr** [comment]
Can you provide more details about the issue?

**Comment by mgdelmonte** [comment]
Same for me, after a reboot, notifications will pop up and play audio when triggered.  However, after a day or so, they stop working.  They go straight to the notification viewer but will not pop up or play audio.  It's as if they're being silenced.

I've ensured that Focus Assist is OFF, and neither python nor powershell nor the appId used for the notification are disallowed from showing notifications or running as background apps, in Windows Settings.

**Comment by gitagogaming** [comment]
So after a reboot, noti's are showing again... 
Not sure what to say about clear notifications as far as more details right now. 
I'll ahve to try and do it some more.. I may have done something wrong.. 


and from a Windows 11 user, when they try and run that code above 

```
Traceback (most recent call last):
  File "c:\Users\Damie\Documents\GitHub\WinTools\main.py", line 8, in <module>
    from utils.util import *
  File "c:\Users\Damie\Documents\GitHub\WinTools\utils\util.py", line 177, in <module>
    notifier = Notifier(r)
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\winotify__init.py", line 224, in init
    self.listener = Listener(self.app_id)
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\winotify_communication.py", line 14, in init
    self.server = MPL(pipe, family='AF_PIPE', authkey=key.encode())
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 451, in init
    self._listener = PipeListener(address, backlog)
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 650, in init__
    self._handle_queue = [self._new_handle(first=True)]
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 663, in _new_handle
    return _winapi.CreateNamedPipe(
PermissionError: [WinError 5] Access is denied

**Comment by versa-syahptr** [comment]
@gitagogaming well, I think that issue comes from the callback feature. Indeed, this feature is not very stable yet, because it has not been tested on other machine (especially in windows 11). I'm gonna make the Notifier class works for those who don't need a callback feature in the next patch

**Comment by ArdaPy** [comment]
> It will be available soon, I'll just do some final checks before release it

Sorry if it is not allowed to quote here but I really appreciate what you are doing. Thank you for your effort.
