### ISSUE TITLE
Error when trying to run the example script

### ISSUE THREAD

**Issue by Tosh0kan** [versa-syahptr/winotify#28]
**Describe the bug**
I try to get run the example script 
```py
from winotify import Notification

toast = Notification(app_id="windows app",
                     title="Winotify Test Toast",
                     msg="New Notification!")

toast.show()
```
But get the following error
```bash
Traceback (most recent call last):
  File "D:\01 Libraries\Documents\Tosh0kan Studios\Coding\MangaDex Feed Notifier\_toaster.pyw", line 8, in <module>
    toast.show()
  File "C:\Users\igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\winotify\__init__.py", line 197, in show
    _run_ps(command=self.script)
  File "C:\Users\igor\AppData\Local\Programs\Python\Python311\Lib\site-packages\winotify\__init__.py", line 72, in _run_ps
    subprocess.Popen(
  File "C:\Users\igor\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\igor\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2]  The system cannot find the file specified 
```
What's happening

**To Reproduce**
1. Paste the example code on a `.py` file
2. Run it
3. See error

**Expected behavior**
The program to run and the notification to show up.

**Desktop (please complete the following information):**
 - Windows 10 Pro 21H2
 - Windows Powershell Version 5.1.19041.1320
 - Output from ```script``` property of the toast after ```build()``` the notification

**Comment by Tosh0kan** [comment]
After looking around in the internet, I found out that the issue was that Powershell wasn't on my PATH variable. Once I added it, Winotify works fine.
